# Generated by Django 6.1.1 on 2026-09-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='bio_text',
        ),
        migrations.AddField(
            model_name='profile',
            name='join_date',
            field=models.DateField(auto_now_add=True, default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_img_url',
            field=models.URLField(blank=True),
        ),
    ]
