# Generated by Django 6.1.1 on 2026-09-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0002_rename_bio_profile_bio_text_profile_join_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_img_url',
            new_name='profile_image_url',
        ),
    ]
