# Generated by Django 6.1.1 on 2026-10-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0004_alter_post_options_rename_author_post_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_file',
            field=models.FileField(blank=True, upload_to='mini_insta/photos/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
